### ISSUE TITLE
Fix XSLT warnings that looks like errors

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-mod-braille#38] opened 2015-08-28 09:18 UTC
![screenshot from 2015-08-28 11 16 12](https://cloud.githubusercontent.com/assets/295481/9543115/71f26270-4d76-11e5-9eca-3fa52163694b.png)

**Comment by bertfrees** [comment] 2015-08-28 09:31
I know, that's very ugly.

**Comment by josteinaj** [comment] 2015-08-28 09:43
Indeed. Without them there's only two messages though, there should probably be more messages output by the scripts as well about what's happening. And those two messages are quite useful but at the same time quite technical; is it possible to make them more human-readable?

**Comment by bertfrees** [comment] 2015-08-28 10:03
Yes you're right, there should be more messages.

It's possible to make those two messages more human-readable. Basically when I select a transformer I print it using `toString`. Maybe transformers could have a nice name as well as a technical name, because the technical name is useful too. Could for example be printed when log level is lower. (Ideally I'd like to see a way in the UI to change the log level on the fly, after conversion, so that more/less messages appear as you move the log level slider.)

**Comment by bertfrees** [comment] 2015-08-28 10:05
... Or the detailed log could be used for technical messages. But I wonder, how does that work? How does the Pipeline find out which log messages belong to which job? Is it something to do with threads?

**Comment by josteinaj** [comment] 2015-08-28 10:12
> Ideally I'd like to see a way in the UI to change the log level on the fly
Yes, I have an idea about collapsible debug messages in the backlog: https://github.com/daisy/pipeline-issues/issues/443

> How does the Pipeline find out which log messages belong to which job?
No idea. Maybe @capitancambio knows?

**Comment by bertfrees** [comment] 2015-12-09 12:26
One type of the XSLT warning is "SXXP0005:The source document is in namespace x, but none of the template rules match elements in this namespace" or "SXXP0005:The source document is in no namespace, but the template rules all expect elements in a namespace". See http://saxon-xslt-and-xquery-processor.13853.n7.nabble.com/SXXP0005-td11887.html for the reason why Saxon produces this warning. Not sure if we can make it go away.

The second type of XSLT warning is "Stylesheet module x is included or imported more than once. This is permitted, but may lead to errors or unexpected behavior". I can probably fix this.

The third type of warning is "XTRE0540: Ambiguous rule match for x ...". We should fix this in the XSLT.

Wouldn't it be possible to filter these kind of warning produced by Saxon itself out (only put them in the detailed log) and only print the ones that we produce ourselves? At the very least they should not look like errors because they are just warnings. @rdeltour and @capitancambio what are your thoughts on this?

**Comment by bertfrees** [comment] 2016-04-19 18:06
See https://github.com/daisy/pipeline-mod-braille/commit/ce7f5459d40b43c65094c866ad7a78ba6977dc57

**Comment by bertfrees** [comment] 2016-04-19 18:07
See https://github.com/snaekobbi/braille-css/commit/b86930a851a9b44029343d56ff80240854e9d8c1

**Comment by bertfrees** [comment] 2016-06-15 16:39
Update:

- In Saxon 9.6, warnings like "The source document is in namespace x, but none of the template rules match elements in this namespace" can be disabled with "--suppressXsltNamespaceCheck:on".
- The warnings were printed as errors because of a bug which I fixed: https://github.com/daisy/pipeline-framework/commit/7786a99dc06a7c0cbc42e0c6f74bf163cabbf042
- Completely filtering out these kind of messages does not seem trivial at first sight. Moving to a new logback-based mechanism for sending messages to the execution log (https://github.com/daisy/pipeline-issues/issues/478) would allow for doing the filtering in config-logback.xml.
- I'm not seeing the warnings in my unit tests because for some reason when invoked through the XProcSpec runner, [this line in Calabash](https://github.com/ndw/xmlcalabash1/blob/34ce556ff41427430c783e661bc33d418482801b/src/com/xmlcalabash/util/StepErrorListener.java#L58) is not called. The way I understand this is that the warning is turned into an XProc error and only when the XProc error is not caught, the warning is passed on.

**Comment by bertfrees** [comment] 2017-08-17 12:58
Reopening because this is not on master yet.

**Closed** 2017-09-14 19:02 UTC
Labels: 2 - In Progress, accepted, bug
